version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.eclipse.jetty:jetty-maven-plugin
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.glassfish.jaxb:jaxb-runtime
    versions:
    - 3.0.0
  - dependency-name: org.controlsfx:controlsfx
    versions:
    - 11.0.3
  - dependency-name: org.gaul:modernizer-maven-plugin
    versions:
    - 2.1.0
