name: Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-java@v2
       with:
         java-version: 20
         distribution: "temurin"
     - uses: actions/setup-node@v3
       with:
          node-version: '16'
     - run: npm install electron-packager -g
     - run: npm install cordova -g
     - run: npm install bower -g
     - run: npm install vulcanize -g
     - run: mvn verify
     - uses: actions/upload-artifact@v1
       with:
         name: Games
         path: 'examples/target/games'
